# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.form.registration:
        class: BourgMapper\TubBundle\Form\Type\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }

    app.form.profile:
        class : BourgMapper\TubBundle\Form\Type\ProfileType
        tags:
            - { name: form.type, alias: app_user_profile }

    app.form.change_password:
        class : BourgMapper\TubBundle\Form\Type\ProfileType
        tags:
            - { name: form.type, alias: app_user_change_password }

    app.form.stop:
        class : BourgMapper\TubBundle\Form\Type\StopType
        tags:
            - { name: form.type, alias: app_stop }

    app.form.line:
        class : BourgMapper\TubBundle\Form\Type\LineType
        tags:
            - { name: form.type, alias: app_line }

    app.form.oauth_client:
        class : BourgMapper\TubBundle\Form\Type\OAuthClientType
        tags:
            - { name: form.type, alias: app_oauth_client }


# service_name:
#        class: TubBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]



