<?php

namespace AppBundle\Entity\Repository;

use AppBundle\AppBundle;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * StopGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StopGroupRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     * @param $line_id
     */
    public function findStopsOfLine($line_id)
    {
        $em = $this->getEntityManager();
        $stopRepository = $em->getRepository("AppBundle:Stop");

        $stop_ids = $this->getEntityManager()
            ->createQuery(
                "SELECT DISTINCT 'stop_id' FROM AppBundle:StopGroup sg WHERE 'line_id' = $line_id"
            )
            ->getArrayResult();

        $stops = array();

        foreach ($stop_ids as $id) {
            $stops->add($stopRepository->find($id));
        }

        return $stops;
    }

    /**
     * @return array
     * @param $stop_id
     */
    public function findLinesOfStop($stop_id)
    {

        $em = $this->getEntityManager();
        $lineRepository = $em->getRepository("AppBundle:Line");

        $line_ids = $this->getEntityManager()
            ->createQuery(
                "SELECT distinct 'line_id' FROM AppBundle:StopGroup sg WHERE 'stop_id' = $stop_id"
            )
            ->getArrayResult();

        $lines = array();

        foreach ($line_ids as $id) {
            $lines->add($lineRepository->find($id));
        }

        return $lines;
    }


}
