<?php
namespace AppBundle\Entity\Repository;

use AppBundle\AppBundle;

/**
 * StopRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StopRepository extends \Doctrine\ORM\EntityRepository
{
}
