-- MySQL Script generated by MySQL Workbench
-- Fri Oct 21 09:42:43 2016
-- Model: First DataBase    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tub
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tub` ;

-- -----------------------------------------------------
-- Schema tub
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tub` DEFAULT CHARACTER SET utf8 ;
USE `tub` ;

-- -----------------------------------------------------
-- Table `tub`.`Lane`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tub`.`Lane` ;

CREATE TABLE IF NOT EXISTS `tub`.`Lane` (
  `id` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `color` VARCHAR(28) CHARACTER SET 'utf8' NOT NULL,
  `name` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `tub`.`Path`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tub`.`Path` ;

CREATE TABLE IF NOT EXISTS `tub`.`Path` (
  `id` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `direction` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `available` TINYINT(1) NULL DEFAULT NULL,
  `lane_id` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `IDX_AB662431A128F72F` (`lane_id` ASC),
  CONSTRAINT `FK_AB662431A128F72F`
    FOREIGN KEY (`lane_id`)
    REFERENCES `tub`.`Lane` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `tub`.`Stop`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tub`.`Stop` ;

CREATE TABLE IF NOT EXISTS `tub`.`Stop` (
  `id` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `name` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `coordinates` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `available` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `tub`.`StopInfo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tub`.`StopInfo` ;

CREATE TABLE IF NOT EXISTS `tub`.`StopInfo` (
  `id` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `stop_id` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `path_id` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `IDX_EC23C3413902063D` (`stop_id` ASC),
  INDEX `IDX_EC23C341D96C566B` (`path_id` ASC),
  CONSTRAINT `FK_EC23C3413902063D`
    FOREIGN KEY (`stop_id`)
    REFERENCES `tub`.`Stop` (`id`),
  CONSTRAINT `FK_EC23C341D96C566B`
    FOREIGN KEY (`path_id`)
    REFERENCES `tub`.`Path` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `tub`.`Schedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tub`.`Schedule` ;

CREATE TABLE IF NOT EXISTS `tub`.`Schedule` (
  `id` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `ETA` TIME NULL DEFAULT NULL,
  `available` TINYINT(1) NULL DEFAULT NULL,
  `stopInfo_id` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `IDX_A34E73ADD3355803` (`stopInfo_id` ASC),
  CONSTRAINT `FK_A34E73ADD3355803`
    FOREIGN KEY (`stopInfo_id`)
    REFERENCES `tub`.`StopInfo` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `tub`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tub`.`User` ;

CREATE TABLE IF NOT EXISTS `tub`.`User` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(180) CHARACTER SET 'utf8' NOT NULL,
  `username_canonical` VARCHAR(180) CHARACTER SET 'utf8' NOT NULL,
  `email` VARCHAR(180) CHARACTER SET 'utf8' NOT NULL,
  `email_canonical` VARCHAR(180) CHARACTER SET 'utf8' NOT NULL,
  `enabled` TINYINT(1) NOT NULL,
  `salt` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `password` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `last_login` DATETIME NULL DEFAULT NULL,
  `locked` TINYINT(1) NOT NULL,
  `expired` TINYINT(1) NOT NULL,
  `expires_at` DATETIME NULL DEFAULT NULL,
  `confirmation_token` VARCHAR(180) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `password_requested_at` DATETIME NULL DEFAULT NULL,
  `roles` LONGTEXT CHARACTER SET 'utf8' NOT NULL COMMENT '(DC2Type:array)',
  `credentials_expired` TINYINT(1) NOT NULL,
  `credentials_expire_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UNIQ_2DA1797792FC23A8` (`username_canonical` ASC),
  UNIQUE INDEX `UNIQ_2DA17977A0D96FBF` (`email_canonical` ASC),
  UNIQUE INDEX `UNIQ_2DA17977C05FB297` (`confirmation_token` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
