<?php

namespace AppBundle\Entity;

/**
 * StopRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StopRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLineOfStop($id)
    {
        $lineList = new \Doctrine\Common\Collections\ArrayCollection();

        $em = $this->getEntityManager();
        $stopGroupTableName = $em->getClassMetadata('AppBundle:StopGroup')->getTableName();
        $tripTableName = $em->getClassMetadata('AppBundle:Trip')->getTableName();

        $qb = $em->createQueryBuilder();

        $tripIds = $qb->select("DISTINCT stop_id")
            ->from("$stopGroupTableName,sg")
            ->where("sg.stop_id = $id");

        $lineIds = $qb->select("DISTINCT line_id")
            ->from("$tripTableName,t")
            ->where("t.id IN $tripIds");

        $lineRepository = $em->getRepository("AppBundle:Line");
        foreach ($lineIds as $lineId) {
            $lineList->add($lineRepository->find($lineId));
        }
        return $lineList;
    }
}
