<?php
namespace BourgMapper\TubBundle\Entity\Repository;

use BourgMapper\TubBundle\Entity;
use Doctrine\Common\Collections\ArrayCollection as ArrayCollection;
use Doctrine\ORM\EntityRepository as EntityRepository;


/**
 * PeriodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeriodRepository extends EntityRepository
{

    const DAY_MONDAY = "monday";
    const DAY_TUESDAY = "tuesday";
    const DAY_WEDNESDAY = "wednesday";
    const DAY_THURSDAY = "thursday";
    const DAY_FRIDAY = "friday";
    const DAY_SATURDAY = "saturday";
    const DAY_SUNDAY = "sunday";

}
